data: 'adni'
data_param:
  train_data_param:
    data_path: /data/datasets/SyntheticDataForKernelTransformer/train_data2.npy
    label_path: /data/datasets/SyntheticDataForKernelTransformer/train_label2.pkl
    random_choose: True
    center_choose: False
    random_noise: True
    random_scale: True
    window_size: 200
    final_size: 180
    num_skip_frame:
    decouple_spatial: False
  val_data_param:
    data_path: /data/datasets/SyntheticDataForKernelTransformer/test_data2.npy
    label_path: /data/datasets/SyntheticDataForKernelTransformer/test_label2.pkl
    random_choose: True
    center_choose: False
    random_noise: False
    random_scale: False
    window_size: 200
    final_size: 180
    num_skip_frame:
    decouple_spatial: False
    augtimes: 1

# model
model: 'dstanet'
class_num: 2
model_param:
  num_point: 42
  num_frame: 180
  num_subset: 6
  num_channel: 6
  num_person: 1
  glo_reg_s: False
  att_s: True
  glo_reg_t: False
  att_t: False
  dropout: 0
  attentiondrop: 0
  dropout2d: 0
  use_spatial_att: True
  use_temporal_att: False
  use_pet: True
  use_pes: True
  kernelattention: True
  diffusion: 5
  config: [[64, 64, 16, 1], [64, 64, 16, 1],
         [64, 128, 32, 2], [128, 128, 32, 1],
         ]


train: 'classify'
mode: 'train_val'
loss: 'cross_entropy'
batch_size: 10
worker: 32
pin_memory: False
num_epoch_per_save: 200
model_saved_name: './work_dir/adni/'
last_model:
pre_trained_model:
ignore_weights: ['fc']
label_smoothing_num: 0
mix_up_num: 0
device_id: [0]
cuda_visible_device: '0'
debug: False

# lr
lr_scheduler: 'reduce_by_epoch'
lr_param:
  step: [60, 80]
#  lr_patience: 10
#  lr_threshold: 0.0001
#  lr_delay: 0
warm_up_epoch: 5
max_epoch: 100
lr: 0.1
wd: 0.0005
lr_decay_ratio: 0.1
lr_multi_keys: []

# optimizer
optimizer: 'sgd_nev'
freeze_keys: []

